// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcProject.Repositories;

#nullable disable

namespace MvcProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241218144919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcProject.Models.Entity.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "George Orwell",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Evie Pom",
                            Nationality = "German"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Leo Tolstoy",
                            Nationality = "Russian"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jane Austen",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gabriel Garcia Marquez",
                            Nationality = "Colombian"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Homer",
                            Nationality = "Ancient Greek"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mark Twain",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Virginia Woolf",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Haruki Murakami",
                            Nationality = "Japanese"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kurt Vonnegut",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Emily Bronte",
                            Nationality = "English"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Raymond Chandler",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Thomas Pynchon",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Marlon James",
                            Nationality = "American"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
