// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcProject.Repositories;

#nullable disable

namespace MvcProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcProject.Models.Entity.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "George Orwell",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Evie Pom",
                            Nationality = "German"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Leo Tolstoy",
                            Nationality = "Russian"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jane Austen",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gabriel Garcia Marquez",
                            Nationality = "Colombian"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Homer",
                            Nationality = "Ancient Greek"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mark Twain",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Virginia Woolf",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Haruki Murakami",
                            Nationality = "Japanese"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kurt Vonnegut",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Emily Bronte",
                            Nationality = "English"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Raymond Chandler",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Thomas Pynchon",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Marlon James",
                            Nationality = "American"
                        });
                });

            modelBuilder.Entity("MvcProject.Models.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            Title = "The Analects",
                            Year = -475
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 4,
                            Title = "Evie’s Adventure",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 6,
                            Title = "War and Peace",
                            Year = 1869
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 10,
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 14,
                            Title = "One Hundred Years of Solitude",
                            Year = 1967
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Title = "The Odyssey",
                            Year = -800
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 14,
                            Title = "The Adventures of Tom Sawyer",
                            Year = 1876
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 14,
                            Title = "Mrs Dalloway",
                            Year = 1925
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            Title = "Norwegian Wood",
                            Year = 1987
                        });
                });

            modelBuilder.Entity("MvcProject.Models.Entity.Book", b =>
                {
                    b.HasOne("MvcProject.Models.Entity.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MvcProject.Models.Entity.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
